`timescale 1ns/1ps

module dff_tb;
reg clk;
reg D;
wire Q;
dff uut(
    .clk(clk),
    .D(D),
    .Q(Q)
);
always #5 clk = ~clk;
initial begin

    $dumpfile("dff.vcd");
    $dumpvars(0,dff_tb);

    clk = 0;

    D = 0;
    #10;

    D = 1;
    #10;

    D = 0;
    #10;

    D = 1;
    #10;

    $finish;
    
end
    
endmodule